/*
 *  ======== config.c ========
 *  Configuration-specific definitions
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool for
 *  the TI Sensors in this application.
 */
#include <stdint.h>

#include "TMP102.h"

#include "config.h"

/*
 *  ======== TMP102_0 ========
 *  TMP102 Sensor configuration settings
 */
static TMP102_State TMP102_0_state = {
    .config = (TMP102_CONFIG_OS_DISABLE | \
               TMP102_CONFIG_F_1FAULT | \
               TMP102_CONFIG_POL_LOW | \
               TMP102_CONFIG_TM_COMP | \
               TMP102_CONFIG_SD_CC | \
               TMP102_CONFIG_CR_4HZ | \
               TMP102_CONFIG_EM_12BIT),
    .tlow = 0x4B00U, /* Temperature Low Limit is 75 Celsius */
    .thigh = 0x5000U, /* Temperature High Limit is 80 Celsius */

    /* Sensor's I2C bus ID and address */
    .busId   = 0,
    .devAddr = 0x48U,

    /* one-shot delay time (ms) */
    .osWait  = 35
};
const TMP102_Handle TMP102_0 = &TMP102_0_state;

