/*
 *  ======== TMP102.c ========
 *  TMP102 APIs for initialization and use of the TMP102 peripheral
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool for
 *  the TI Sensors in this application.
 */

#include <stddef.h>
#include <stdint.h>

#include "TMP102.h"
#include "mcu.h"

#define MSB(u16) (((u16) & 0xFF00U) >> 8)
#define LSB(u16) ((u16) & 0xFFU)

/*
 *  ======== writeReg ========
 */
static void writeReg(TMP102_Handle sensor, int regAddr, uint16_t value)
{
    uint8_t txBuf[3];

    txBuf[0] = regAddr;
    txBuf[1] = MSB(value);
    txBuf[2] = LSB(value);
    mcu_i2cTransfer(sensor->busId, sensor->devAddr, txBuf, 3, NULL, 0);
}

/*
 *  ======== TMP102_config ========
 * Configure device with current settings.
 */
void TMP102_config(TMP102_Handle sensor)
{
    /* Initialize the bus containing this sensor */
    mcu_i2cInit(sensor->busId);

    /* Write sensor Configuration Register */
    writeReg(sensor, TMP102_CONFIG, sensor->config);

    /* Write sensor Temperature High and Low Registers */
    writeReg(sensor, TMP102_THIGH, sensor->thigh);
    writeReg(sensor, TMP102_TLOW, sensor->tlow);
}

/*
 *  ======== TMP102_read ========
 *  Read temperature register
 */
int32_t TMP102_read(TMP102_Handle sensor)
{
    uint8_t txBuf[1];
    uint8_t rxBuf[2] = {0};
    int32_t tmp;

    /* If needed, setup one shot measurement */
    if (sensor->config & TMP102_CONFIG_SD_SD) {
        /* Reset one shot enable */
        writeReg(sensor, TMP102_CONFIG, sensor->config | TMP102_CONFIG_OS_ENABLE);

        /* Wait for conversion to complete */
        mcu_msWait(sensor->osWait);
    }

    /* Read temperature register */
    txBuf[0] = TMP102_TEMP;
    mcu_i2cTransfer(sensor->busId, sensor->devAddr, txBuf, 1, rxBuf, 2);

    /* Sign extend and combine MSB with LSB */
    tmp = (((int32_t)(int8_t)rxBuf[0]) << 8) | rxBuf[1];

    return (tmp);
}


/*
 *  ======== TMP102_toIntCelsius ========
 *  Convert raw temperature register value to degrees Celsius rounded to the
 *  nearest integer
 */
int32_t TMP102_toIntCelsius(TMP102_Handle sensor, int32_t x)
{
    /* Shift raw register value, based on config, to form a Q4 value */
    x >>= (sensor->config & (uint8_t)(TMP102_CONFIG_EM_13BIT)) ? 3 : 4;

    /* Optional: Add bias to round before the final truncation */
    x += (x >= 0) ? (1 << 3) : -(1 << 3);

    /* Convert Q4 value to whole number */
    x /= 1 << 4; /* use division so small negative values round to 0 */

    return x;
}

/*
 *  ======== TMP102_toMilliCelsius ========
 *  Convert raw temperature register value to milli-degrees Celsius
 */
int32_t TMP102_toMilliCelsius(TMP102_Handle sensor, int32_t x)
{
    /* Shift raw register value, based on config, to form a Q4 value */
    x >>= (sensor->config & (uint8_t)(TMP102_CONFIG_EM_13BIT)) ? 3 : 4;

    /* Scale to milli-degrees, convert Q4 value to a whole number */
    return ((1000 * x) >> 4);
}

/*
 *  ======== TMP102_toFloatCelsius ========
 *  Convert raw temperature register value to degrees Celsius
 */
float TMP102_toFloatCelsius(TMP102_Handle sensor, int32_t x)
{
    /* Shift raw register value, based on config, to form a Q4 value */
    x >>= (sensor->config & (uint8_t)(TMP102_CONFIG_EM_13BIT)) ? 3 : 4;

    /* Convert Q4 value to a float */
    return ((float)x * 0.0625f);
}

